# Generated by Django 5.2.4 on 2025-08-04 14:36
import phonenumbers
from django.db import migrations


def normаlise_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all().iterator()
    for flat in flats:
        try:
            parsed_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        except NumberParseException:
            print("Номер пустой или сильно некорректный")
        if phonenumbers.is_valid_number(parsed_number):
            pure_number = phonenumbers.format_number(parsed_number, phonenumbers.PhoneNumberFormat.E164)
            flat.owner_pure_phone = pure_number
            flat.save(update_fields=['owner_pure_phone'])
        else:
            flat.owner_pure_phone = None
            flat.save(update_fields=['owner_pure_phone'])


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(normаlise_numbers)
    ]
