# Generated by Django 5.2.4 on 2025-08-09 09:28

from django.db import migrations

def migrate_owners_to_owner_model(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        Owner.objects.get_or_create(owner_name=flat.owner, pure_phonenumber=flat.owner_pure_phone, phonenumber=flat.owners_phonenumber)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [
        migrations.RunPython(migrate_owners_to_owner_model)
    ]
