# Generated by Django 5.2.4 on 2025-08-10 11:34
from django.db import migrations


def link_flat_and_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    flats_by_phone = {}
    for flat in Flat.objects.all():
        if flat.owner_pure_phone:
            flats_by_phone.setdefault(flat.owner_pure_phone, []).append(flat)

    for owner in Owner.objects.iterator():
        if owner.pure_phonenumber:
            matching_flats = flats_by_phone.get(owner.pure_phonenumber, [])
            owner.flats.set(matching_flats)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20250809_1228'),
    ]

    operations = [
        migrations.RunPython(link_flat_and_owner)
    ]
